apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: postgres-ssd:5432
    database: webservices
    user: ${POSTGRES_PIPELINE_USER}
    isDefault: false
    editable: false
    uid: timescaledb
    secureJsonData:
      password: ${POSTGRES_PIPELINE_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
